import '../tinymce.min.js'
import '../themes/silver/theme.min.js'
import '../themes/mobile/theme.min.js'
import '../langs/zh_CN.js';
import '../icons/default';
import '../plugins/fullscreen';
import '../plugins/indent2em';
import '../plugins/advlist';
import '../plugins/autolink';
import '../plugins/link';
import '../plugins/image';
import '../plugins/charmap';
import '../plugins/preview';
import '../plugins/table';
import '../plugins/example';
import '../plugins/lists';
import '../plugins/code';
import '../plugins/autoresize';
import '../plugins/fileupload';